name: Test Optimum

on:
  workflow_dispatch:
  push:
  pull_request:
    paths:
      - "modules/optimum/**"
      - ".github/workflows/test_optimum.yml"

jobs:
  test_nncf:
    name: "NNCF"

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        nncf-version: [
          "git+https://github.com/openvinotoolkit/nncf.git@90a48c93d08f859dd648b1612f65c5d7ed59c34b",
          "git+https://github.com/openvinotoolkit/nncf.git@5f162c98b2e54ecacf21c56b2396c7f00b7d8bd9"
        ]
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install package
      working-directory: modules/optimum
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[nncf] 

    - name: Install test dependencies
      working-directory: modules/optimum/tests/nncf
      run: |
        pip uninstall -y nncf
        python -m pip install ${{ matrix.nncf-version }} -r requirements.txt
        sudo apt-get install -y libsndfile1

    - name: pip freeze
      run: |
        pip freeze

    - name: Prepare examples
      working-directory: modules/optimum/tests/nncf
      run: |
        wget https://raw.githubusercontent.com/huggingface/transformers/v4.15.0/examples/pytorch/token-classification/run_ner.py -P examples/pytorch/token-classification
        wget https://raw.githubusercontent.com/huggingface/transformers/v4.15.0/examples/pytorch/audio-classification/run_audio_classification.py -P examples/pytorch/audio-classification
        patch -p1 < run_ner.patch
        patch -p1 < run_audio_classification.patch

    - name: Test NNCF
      working-directory: modules/optimum/tests/nncf
      run: |
        cp ../../optimum/intel/nncf/configs/* .
        python -m unittest -v test_nncf.NNCFTests.test_bert_base_ner
